openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /health:
    get:
      tags:
      - health
      summary: Health status
      description: Basic health status.
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
  /v1/db/scrape_url:
    get:
      tags:
      - scrapping
      summary: Will scraped data to database.
      operationId: db_scrape_url_v1_db_scrape_url_get
      parameters:
      - name: url
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Url
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScrapResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/db/read_db:
    get:
      tags:
      - scrapping
      summary: Reads scraped data from database.
      operationId: db_scrape_url_v1_db_read_db_get
      parameters:
      - name: url
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Url
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScrapResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HealthStatus:
      properties:
        status:
          type: string
          title: Status
      type: object
      required:
      - status
      title: HealthStatus
      description: Model for health check.
    ScrapResponse:
      properties:
        url:
          anyOf:
          - type: string
          - type: 'null'
          title: Url
          description: The URL from which data were be scraped.
          examples:
          - https://example.com
        text:
          anyOf:
          - type: string
          - type: 'null'
          title: Text
          description: Data scraped from url
          examples:
          - Some text
        job:
          anyOf:
          - type: string
          - type: 'null'
          title: Job
          description: The job that was done.
          examples:
          - saved_to_db
          - read_from_db
      type: object
      title: ScrapResponse
      description: Model for a response with scraped data from a given URL.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
